name: rudiproducer
services:
  rudi-db:
    image: rudinode-dc
    build:
      context: .
      dockerfile: Dockerfile.build
      network: host
    container_name: rudi_db
    restart: no
    ports:
      - 27017:27017
    volumes:
      - ./data:/data:rw
    environment:
      ENABLE_DB: 'true'
      ENABLE_CATALOG: 'false'
      ENABLE_STORAGE: 'false'
      ENABLE_MANAGER: 'false'
    network_mode: host

  rudi-manager:
    image: rudinode-dc
    container_name: rudi_manager
    restart: no
    ports:
      - 3032:3032
    volumes:
      - ./data:/data:rw
    environment:
      NODE_PUBLIC_URL: http://localhost
      ENABLE_DB: 'false'
      ENABLE_CATALOG: 'false'
      ENABLE_STORAGE: 'false'
      ENABLE_MANAGER: 'true'
    network_mode: host
    depends_on:
      - rudi-storage
      - rudi-catalog

  rudi-catalog:
    image: rudinode-dc
    container_name: rudi_catalog
    restart: no
    ports:
      - 3030:3030
    volumes:
      - ./data:/data:rw
    environment:
      NODE_PUBLIC_URL: http://localhost
      ENABLE_DB: 'false'
      ENABLE_CATALOG: 'true'
      ENABLE_STORAGE: 'false'
      ENABLE_MANAGER: 'false'
    network_mode: host
    depends_on:
      - rudi-db

  rudi-storage:
    image: rudinode-dc
    container_name: rudi_storage
    restart: no
    ports:
      - 3031:3031
    volumes:
      - ./data:/data:rw
    environment:
      NODE_PUBLIC_URL: http://127.0.0.1
      ENABLE_DB: 'false'
      ENABLE_CATALOG: 'false'
      ENABLE_STORAGE: 'true'
      ENABLE_MANAGER: 'false'
    network_mode: host
    depends_on:
      - rudi-db
