FROM node:20-alpine as NodeBuilder

# Folder that contains the source of every rudi-node module
ARG SRC_DIR="./src"
ARG PUBLIC_URL=""

ENV WK_DIR="/app/rudi-node"
ENV INI_DIR="$WK_DIR/ini"
ENV NODE_ENV=production

WORKDIR "$WK_DIR"
RUN apk update && apk add python3 xz

COPY ./env/* "$WK_DIR"/

ENV NPM_INSTALL="npm install --no-audit  --verbose"
RUN npm config set registry http://registry.npmjs.org/ && \
    npm config set fetch-timeout 1000 && \
    npm config set package-lock false && \
    npm config set progress false && \
    npm config set loglevel warn && \
    npm config set @aqmo.org:registry "https://gitlab.aqmo.org/api/v4/projects/59/packages/npm/"

RUN addgroup -g 5001 rudi && \
    addgroup -g 5002 rudicatalog && \
    addgroup -g 5003 rudistorage && \
    addgroup -g 5004 rudicrypto && \
    addgroup -g 5005 rudimanager

RUN adduser -D -G rudi        -u 5001 rudiadm && \
    adduser -D -G rudicatalog -u 5002 rudicatalog && \
    adduser -D -G rudistorage -u 5003 rudistorage && \
    adduser -D -G rudicrypto  -u 5004 rudicrypto && \
    adduser -D -G rudimanager -u 5005 rudimanager && \
    addgroup rudicatalog rudi && \
    addgroup rudistorage rudi && \
    addgroup rudicrypto  rudi && \
    addgroup rudimanager rudi

COPY ${SRC_DIR}/rudi-crypto ${WK_DIR}/rudi-crypto
COPY ${SRC_DIR}/rudi-catalog ${WK_DIR}/rudi-catalog
COPY ${SRC_DIR}/rudi-storage ${WK_DIR}/rudi-storage
COPY ${SRC_DIR}/rudi-manager ${WK_DIR}/rudi-manager

COPY ./install/searchPackages.py /app/searchPackages.py
RUN python3 /app/searchPackages.py > package.json && ${NPM_INSTALL}

RUN ( cd rudi-catalog && ${NPM_INSTALL} )
RUN ( cd rudi-storage && ${NPM_INSTALL} )
RUN ( cd rudi-crypto  && ${NPM_INSTALL} )
RUN ( cd rudi-manager && ${NPM_INSTALL} )
RUN ( cd rudi-manager/front && NODE_ENV='development' ${NPM_INSTALL} )

ENV PUBLIC_URL=${PUBLIC_URL}
RUN ( cd rudi-manager/front && npm run build:prod  )

RUN chown -R rudiadm:rudi     node_modules *.ini *.json && \
    chown -R rudicatalog:rudi rudi-catalog  && \
    chown -R rudistorage:rudi rudi-storage  && \
    chown -R rudicrypto:rudi  rudi-crypto   && \
    chown -R rudimanager:rudi rudi-manager

RUN chmod -R u=rwX,g=X,o= rudi-catalog rudi-storage rudi-crypto rudi-manager && \
    chmod -R u=rwX,g=rX,o= node_modules  *.ini *.json

RUN ( cd /app && tar --exclude rudi-manager/front/node_modules --exclude rudi-manager/front/src --exclude '.git' -Jcvf /app/rudi-node.tar.xz rudi-node )

RUN apk add squashfs-tools
RUN mksquashfs /app/rudi-node /app/rudi-node.iso -comp xz -b 4096 -wildcards -e rudi-manager/front/src -e rudi-manager/front/node_modules -e '... .git'

FROM ubuntu:noble as system

WORKDIR /home/ferretdb
ADD https://deb.nodesource.com/setup_20.x                                                        /home/ferretdb/nodejs_setup.sh
ADD https://github.com/FerretDB/FerretDB/releases/download/v1.23.1/ferretdb-linux-amd64.deb      /home/ferretdb/ferretdb-linux-amd64.deb
ADD https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.10.0.deb    /home/ferretdb/mongodb-database-tools.deb

RUN apt update && \
    apt -y dist-upgrade && \
    /bin/bash /home/ferretdb/nodejs_setup.sh && \
    apt update && DEBIAN_FRONTEND=noninteractive apt install -y adduser nodejs xz-utils libgssapi-krb5-2 libkrb5-3 libk5crypto3 libkrb5support0 libkeyutils1 && \
    dpkg -i ferretdb-linux-amd64.deb mongodb-database-tools.deb && \
    apt -y autoremove && apt clean && rm -rf *.deb /var/lib/apt/lists/*

RUN addgroup --gid 5001 rudi && \
    addgroup --gid 5002 rudicatalog && \
    addgroup --gid 5003 rudistorage && \
    addgroup --gid 5004 rudicrypto && \
    addgroup --gid 5005 rudimanager

RUN adduser --disabled-password --ingroup rudi        --uid 5001 rudiadm && \
    adduser --disabled-password --ingroup rudicatalog --uid 5002 --ingroup rudi rudicatalog && \
    adduser --disabled-password --ingroup rudistorage --uid 5003 --ingroup rudi rudistorage && \
    adduser --disabled-password --ingroup rudicrypto  --uid 5004 --ingroup rudi rudicrypto && \
    adduser --disabled-password --ingroup rudimanager --uid 5005 --ingroup rudi rudimanager

WORKDIR /app

COPY --from=NodeBuilder /app/rudi-node.tar.xz rudi-node.tar.xz
RUN tar -Jxf rudi-node.tar.xz && rm rudi-node.tar.xz

# ferretdb --handler=sqlite --sqlite-url=file:/home/ferretdb/db/ --log-level=WARN  > ferretdb.log 2> ferretdb.err

CMD /bin/bash -l
