; Each profile their own section

;--------------------------------------------------------------------------
; RUDI producer node - ProdmanagerManager module
;--------------------------------------------------------------------------
[rudi_node_manager]
pub_key=/.ssh/catalog_mngr.pub
routes[]="all"

;--------------------------------------------------------------------------
; Postman
;--------------------------------------------------------------------------
[postman]
pub_key=/.ssh/postman.pub
routes[]="all"
